name: Validate JSON
on: [push]
jobs:
  basic-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Run through jq
      run: cat tallycash.tokenlist.json | jq empty
